export const SET_BUILD_CARDS_SET_LENGTH = 'SET_BUILD_CARDS_SET_LENGTH'
export const CLEAR_BUILD_HISTORY = 'CLEAR_BUILD_HISTORY'
export const ADD_BUILD_HISTORY_ITEMS = 'ADD_BUILD_HISTORY_ITEMS'

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'

export const READ_SETTINGS_FROM_LOCAL_STORAGE = 'READ_SETTINGS_FROM_LOCAL_STORAGE'
export const SAVE_INPUT_SETTINGS = 'SAVE_INPUT_SETTINGS'
